routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});
Route::get('/forget_password', function () {
    return view('forget_password');
});
Route::get('/resetpassword', function () {
    return view('reset_password');
});
Route::get('/dashboard', 'AccountController@index')->middleware('authenticated');

Route::get('/signup','listController@index');

Route::get('/contact_us', function () {
    return view('contact_us');
});

Route::get('/profile', function () {
    return view('profile');
})->middleware('authenticated');

Route::get('/edit_profile', function () {
    return view('edit_profile');
})->middleware('authenticated');

Route::get('/create_account', function () {
    return view('create_account');
})->middleware('authenticated');

Route::get('/history', 'AccountController@history')->middleware('authenticated');
//User Registration 
Route::resource('users', 'UserController');

Route::post('/periodicTransaction', 'AccountController@periodicUpdate')->middleware('authenticated');

//Open Account
Route::resource('accounts', 'AccountController')->middleware('authenticated');


//User Login 
Route::post('/userlogin', 'AccountController@UserLogin');

Route::get('/logout', 'LogoutController@getSignOut');

Route::post('/forgetpassword', 'LogoutController@sendEmail');

Route::post('/resetpassword', 'LogoutController@setPassword');

Route::post('graph_filter','AccountController@graphfilter')->middleware('authenticated');

Route::get('account_account_transfer', 'AccountController@accountName')->middleware('authenticated');

Route::get('with_in_account', 'AccountController@inAccountTransfer')->middleware('authenticated');

Route::get('periodic_transaction', 'AccountController@periodicTransaction')->middleware('authenticated');

Route::get('/graphs_data', 'AccountController@graphsdata')->middleware('authenticated');

Route::get('/account_setting', 'AccountController@account_setting')->middleware('authenticated');

resources/views/account_account_transfer.blade.php
@extends('layouts.header')
@section('content')


<style>
h3{
    color:white;
}
ul li{
    list-style:none;
}
#snav{
    width:100%;
    margin-left:-40px;
    margin-bottom:2px;
}

</style>
@extends('layouts.side')
<!-- #######################   Profile Division      #################### -->
<div class="col-md-9" style="background-color: white; height: 100vh;">
<br>
<div class="col-md-8 col-md-offset-2" style="background-color: white;box-shadow:1px 1px 5px black; height: 90vh;">
<center>
<img src="https://cdn2.iconfinder.com/data/icons/webstore/512/dollar_money_bag-512.png" style="width:15%;">
<h4>Account to Account Transfer</h4>
<center>
@if ($message = Session::get('success'))
    <p style="color:green"><span class="glyphicon glyphicon-ok"></span> {{ $message }}</p>
    <script> myFun();</script>
@endif
@if ($message = Session::get('error'))
    <p style="color:red"><span class="glyphicon glyphicon-remove"></span> {{ $message }}</p>
@endif
</center>
<hr>
</center>
<form action="{{ route('accounts.update', Auth::user()->id) }}" method="POST">
{{ method_field('PUT') }}
    {{ csrf_field() }}
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="account">From Account</label>
    <select class="form-control" name="from_account">
    <option>Select</option>
    @foreach($accounts_data as $user)
        <option value="{{ $user->name}}">{{ $user->name }}</option>
    @endforeach
    </select>
  </div><br>
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="account">To Account</label>
    <select class="form-control" name="to_account">
    <option>Select</option>
    @foreach($accounts_data as $user)
        <option value="{{ $user->name}}">{{ $user->name }}</option>
    @endforeach
    </select>
  </div><br>
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="pwd">Transfer Amount</label>
    <input type="number" class="form-control" name="amount_transfer" placeholder="Enter Amount to be Transfer">
  </div>
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="pwd">Description</label>
    <textarea type="text" class="form-control" name="description" placeholder="Enter Description"></textarea>
  </div>
  <center>
  <div class="form-group col-md-8 col-md-offset-5">
  <button type="submit" style="float:left;" class="btn btn-success">Submit</button>
  </center>
  </div>
</form>
</div>
</div>
</div>@endsection

resources/views/contact_us.blade.php
@extends('layouts.header')
@section('content')
<style>
hr {border-top: 1px solid #000; width:50%;}

a {color: #000;}

a:link{text-decoration:none;}
    
}
#add{
    background-color:#660033;
}
</style>
<div class="container col-md col-md-12" style="margin-top:5vh;">
<div class="container-fluid">
<h1 class="text-center">Contact Address</h1>
<hr>
 <div class="row">
  <iframe src="https://maps.google.com/maps?width=100%&amp;height=300&amp;hl=en&amp;q=Luminoguru%20mohali+(Luminoguru)&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=A&amp;output=embed" width="100%" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
 </div>
	  <div class="col-md-4" id="add">
        <a href="tel:+123456789">
        <h3>Phone</h3>
        <p>+91-7696342418</p></a>
      </div>
      <div class="col-md-4">
        <a href="">
        <h3>Address</h3>
        <p>Plot # E304 ,3rd Floor , Industrial Area Phase 8A, Sector 75, Sahibzada Ajit Singh Nagar, Punjab 160071</p></a>
      </div>
      <div class="col-md-4">
        <a href="mailto:test@test.com">
        <h3>E-mail</h3>
        <p>inamur.luminoguru@gmail.com</p></a>
      </div>
</div>
<div class="row text-center bg-success text-white" id="author">
  <div class="col-md-12">
  <a href="#">by Inamur Rahman</a>
</div>
</div>
    
</div>
@endsection

resources/views/create_account.blade.php
@extends('layouts.header')
@section('content')
<style>
h3{
    color:white;
}
ul li{
    list-style:none;
}
#snav{
    width:100%;
    margin-left:-40px;
    margin-bottom:2px;
}
</style>
<script>
function myFun(){
    $(document).ready(function () {
    window.setTimeout(function () {
        location.href = "/dashboard";
    }, 3000);
});
}
</script>
@extends('layouts.side')
<!-- #######################   Open Account     #################### -->
<div class="col-md-9" style="background-color: white; height: 100vh;"><br><br>
<div class="col-md-8 col-md-offset-2" style="background-color: white;box-shadow:1px 1px 5px black; height: auto;">
<center>
<img src="https://cdn2.iconfinder.com/data/icons/eco-business/512/bank-512.png" style="width:15%;">
<h4>Open Account</h4>
<center>
@if ($message = Session::get('success'))
    <p style="color:green"><span class="glyphicon glyphicon-ok"></span> {{ $message }}</p>
    <script> myFun();</script>
@endif
@if ($message = Session::get('error'))
    <p style="color:red"><span class="glyphicon glyphicon-remove"></span> {{ $message }}</p>
@endif
</center>
<hr>
</center>
<form action="/accounts" method="POST">
{{ csrf_field() }}
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="account">Account Name:</label>
    <input type="text" class="form-control" name="account_name" placeholder="Enter Account Name">
  </div><br>
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="pwd">Initial Balance:</label>
    <input type="number" class="form-control" name="initial_balance" placeholder="Enter Initial Balance">
  </div>
  <center>
  <div class="form-group col-md-8 col-md-offset-5">
  <button type="submit"  style="float:left;" class="btn btn-success"> Open </button>
  </div>
  </center>
  
</form>
<br><br>
</div>
</div>
</div>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.header')
@section('content')
<script>
window.onload = function() {
  <?php
  $ptotal = 0;
  $i = 0;
  $per = [];
  $act_name = [];
  foreach($accounts_data as $user){
    $ptotal = $ptotal+$user['current_balance'];
  }
  foreach($accounts_data as $user){
    $per[$i] = ($user['current_balance']/$ptotal)*100;
    $act_name[$i] = $user['name'];
    $i++;
  }
  $len = sizeof($act_name);
  ?>
var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title: {
		text: "Account's Share"
	},
	data: [{
		type: "pie",
		startAngle: 180,
		yValueFormatString: "##0.00\"%\"",
		indexLabel: "{label} {y}",
		dataPoints: [
    <?php for($j=0;$j<$len;$j++) {?>
			{y: <?php echo $per[$j] ?>, label: "<?php echo $act_name[$j] ?>"},
    <?php } ?>
		]
	}]
});
chart.render();

}
</script>
<style>
h3{
    color:white;
}
ul li{
    list-style:none;
}
#snav{
    width:100%;
    margin-left:-40px;
    margin-bottom:2px;
}
#dmenu{
  width:30%;
  height: 40px;
}
#dmenu:hover{
  box-shadow: 2px 2px 2px black;
}
table th {
    width: auto !important;
}
</style>
@extends('layouts.side')
<!-- #######################   Profile Division      #################### -->
<div class="col-md-9" style="background-color: white; height: 96vh;">
<br>
<center>
<div class="col-md-12" style="width:100%;">      
<table class="table table-striped">
    <thead style="background-color:#660033;">
      <tr style="color: white;">
        <th>Account Name</th>
        <th>Balance</th>
      </tr>
    </thead>
    <tbody>
    <?php $total =0;
    foreach ($accounts_data as $user)
    {
      $total= $total+$user['current_balance'];
    }
    ?>
    @foreach($accounts_data as $user)
      <tr>
        <td>{{ $user->name }}</td>
        <td>$ {{ $user->current_balance }} </td>
      </tr>
    @endforeach
      <tr>
      <th>Total</th>
      <th>
      <?php echo "$ ".$total;?>
      </th>
      </tr>
    </tbody>
  </table>
</div>
</center>
<?php if($len == 0){ ?>
<center>
<img src="img/welcome.png" style="width:30%;"><br>
<a href="/create_account"><p style="color:black; font-size:20px;">You do not have any Account. Please click here to create Account</p></a>
</center>
<?php } else{?>
<div class="col-md-12" id="chartContainer" style="height: 300px; width: 100%;"></div>
<div id="chartContainer" style="height: 300px; width: 100%;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<?php } ?>
</div>
</div>
@endsection

resources/views/forget_password.blade.php
@extends('layouts.header')
@section('content')
<div class="container col-md col-md-4 col-md-offset-4" style="margin-top:30vh;">
<legend>Forget Password</legend>
    <form action="/forgetpassword" method="POST">
    {{ csrf_field() }}
        <div class="form-group">
        <center>
        @if (isset($error))
    <p style="color:red;">{{ $error }}</p>
@endif
             @if (isset($success))
    <p style="color:green;"><span class="glyphicon glyphicon-ok"></span> {{ $success }}</p>
@endif
        </center>
        <label>Enter your E-mail Address</label>
            <input type="text" class="form-control" name="email" placeholder="Enter Email Address">
        </div>
        <center>
        <button type="submit" class="btn" style="background-color:#660033;color: #F0E68C;"> &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-send"></span>&nbsp;Send&nbsp;&nbsp; &nbsp;&nbsp;</button>
        </center>
    </form><br>
</div>
@endsection

resources/views/graphs.blade.php
@extends('layouts.header')
@section('content')


<style>
h3{
    color:white;
}
ul li{
    list-style:none;
}
#snav{
    width:100%;
    margin-left:-40px;
    margin-bottom:2px;
}

</style>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer1", {
	animationEnabled: true,
	exportEnabled: true,
	theme: "light1", // "light1", "light2", "dark1", "dark2"
	title:{
		text:" {{ $heading }} "
	},
	data: [{
		type: "column", //change type to bar, line, area, pie, etc
		//indexLabel: "{y}", //Shows y value on all Data Points
		indexLabelFontColor: "#5A5757",
		indexLabelPlacement: "outside",
		dataPoints: [
			<?php 
			$set = isset($tags_user_name);
			if(! $set){
				$tags_user_name =null;
			}
			else{	
			for($i=0; $i<sizeof($tags_user_name); $i++){ ?>
			{ x: <?php echo $i*10 ?>, y: <?php echo $tags_expnd[$i]; ?>, indexLabel: "<?php echo $tags_user_name[$i]; ?>" },
	        <?php } } ?>
		]
	}]
});
chart.render();

}
</script>
@extends('layouts.side')
<!-- #######################   Profile Division      #################### -->
<div class="col-md-9" style="background-color: white; height: 96vh;">
<br><br>
<form action="/graph_filter" method="POST">
{{ csrf_field() }}
	<div class="form-group col-md-4">
    <label for="date">From:</label>
    <input type="date" class="form-control" name="from_date">
	</div>
	<div class="form-group col-md-4">
    <label for="date">To:</label>
    <input type="date" class="form-control" name="to_date">
	</div>
	<div class="form-group col-md-4">
    <label for="account">Account Name:</label>
	<select class="form-control" name="from_account">
    <option value="null">All Accounts</option>
    @foreach($accounts_name as $user)
        <option value="{{ $user->name}}">{{ $user->name }}</option>
    @endforeach
    </select>
	</div>
	<center> <button type="submit" class="btn" style="background-color:#660033;color: white;"> &nbsp;&nbsp; Show &nbsp;&nbsp;</button></center><br>
</form>
<?php if($set){?>
<br><br>
<div id="chartContainer1" style="height: 300px; width: 100%; float:left;"></div>
<?php } else{ ?>
	<center>
	<br><br><br>
	<img src="img/sorry.jpg" style="width:30%;"><br>
	<p style="color:black; font-size:20px;">No Records Founds <a href="/graphs_data">Click to go back</a></p>
	</center>
<?php } ?>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</center>
</div>
</div>
</div>@endsection

resources/views/history.blade.php
@extends('layouts.header')
@section('content')
<?php
$type = array("Credit", "Debit");
?>
<style>
h3{
    color:white;
}
ul li{
    list-style:none;
}
#snav{
    width:100%;
    margin-left:-40px;
    margin-bottom:2px;
}
#dmenu{
  width:30%;
  height: 40px;
}
#dmenu:hover{
  box-shadow: 2px 2px 2px black;
}
table th {
    width: auto !important;
}
td {
  font-size: 12px;
}
</style>
@extends('layouts.side')
<!-- #######################   Profile Division      #################### -->
<div class="col-md-9" style="background-color: white; height: 96vh;">
<br>
<center>
<div class="col-md-12 table-responsive" style="width:100%;">      
<table class="table responsive table-striped">
    <thead style="background-color:#660033;">
      <tr style="color: white;">
        <th>Transaction History</th>
        <th></th><th></th><th></th><th></th><th></th><th></th>
      </tr>
    </thead>
    <tr>
        <th>Date & Time</th>
        <th>Transaction ID</th>
        <th>Account Name</th>
        <th>Amount</th>
        <th>Type</th>
        <th>Description</th>
        <th>Tags</th>
      </tr>
    <tbody>
    <?php $total =0;
    foreach ($accounts_data as $user)
    {
      $total= $total+$user['current_balance'];
    }
    ?>
    @foreach($transaction_data as $user)
      <tr>
        <td>{{ $user->date }}</td>
        <td>TRAN00{{ $user->id }}</td>
        <td>{{ $user->account_name }}</td>
        <td>$ {{ $user->amount }}</td>
        @if($type[$user->type]=="Debit")
        <td style="color:red;">{{ $type[$user->type] }}</td>
        @else
        <td style="color:darkgreen;">{{ $type[$user->type] }}</td>
        @endif
        <td>{{ $user->description }}</td>
        <td>{{ $user->tags }}</td>
      </tr>
    @endforeach
    </tbody>
  </table>
</div>
{{ $transaction_data->links() }}
</center>
</div>
</div>
@endsection

resources/views/periodic_transaction.blade.php
@extends('layouts.header')
@section('content')


<style>
h3{
    color:white;
}
ul li{
    list-style:none;
}
#snav{
    width:100%;
    margin-left:-40px;
    margin-bottom:2px;
}

</style>

@extends('layouts.side')
<!-- #######################   Profile Division      #################### -->
<div class="col-md-9" style="background-color: white; height: 96vh;">
<br>
<div class="col-md-8 col-md-offset-2" style="background-color: white;box-shadow:1px 1px 5px black; height: auto;">
<center>
<img src="https://cdn3.iconfinder.com/data/icons/office-24/100/Icon_FastSetting2-512.png" style="width:12%;">
<h4>Periodic Transaction</h4>
<center>
@if ($message = Session::get('success'))
    <p style="color:green"><span class="glyphicon glyphicon-ok"></span> {{ $message }}</p>
    <script> myFun();</script>
@endif
@if ($message = Session::get('error'))
    <p style="color:red"><span class="glyphicon glyphicon-remove"></span> {{ $message }}</p>
@endif
</center>
<hr>
</center>
<form action="/periodicTransaction" method="POST">
    {{ csrf_field() }}
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="account">Select Account</label>
    <select class="form-control" name="account">
    <option>Select</option>
    @foreach($accounts_data as $user)
        <option value="{{ $user->name}}">{{ $user->name }}</option>
    @endforeach
    </select>
  </div><br>
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="account">Time Span: </label>
    <select class="form-control" name="time_span">
    <option value="">Select</option>
    <option value="1">1 Day</option>
    <option value="2">1 Week</option>
    <option value="3">1 months</option>
    <option value="4">6 months</option>
    <option value="5">1 Years</option>
    </select>
  </div><br>
  <div class="form-group col-md-8 col-md-offset-2">
    <label id="aid">Amount</label>
    <input type="number" class="form-control" name="amount" placeholder="Enter Amount">
  </div>
  <div class="form-group col-md-8 col-md-offset-2">
    <label id="tid">Description</label>
    <textarea type="text" id="did" class="form-control" name="description" placeholder="Enter description" required></textarea>
  </div>
  <div class="form-group col-md-8 col-md-offset-2">
    <label id="tid">Tags</label>
    <input type="text" id="textid" pattern="[a-z]+([,]+[a-z]+([a-z])?)*" class="form-control" name="tags" title="Seprate the tags with comma and lowercase only.Eg. health,vehicle" placeholder="Enter tags in lower case only using comma. Eg. food,health,vehicle" required>
  </div>

  <center>
  <div class="form-group col-md-8 col-md-offset-5">
  <button type="submit" style="float:left; width:30%;" class="btn btn-success">Submit</button>
  </div>
  </center>
</form>
<br><br>

</div>

</div>
</div>@endsection

resources/views/reset_password.blade.php
<script>

</script>
@extends('layouts.header')
@section('content')
<div class="container col-md col-md-4 col-md-offset-4" style="margin-top:25vh;">
<legend>Reset Password</legend>
<center>
@if (isset($success))
    <p style="color:green"><span class="glyphicon glyphicon-ok"></span> {{ $success }}</p>
@endif
@if (isset($error))
    <p style="color:red"></span> {{ $error }}</p>
@endif
</center>
    <form action="/resetpassword" method="POST">
    {{ csrf_field() }}
        <div class="form-group">
        <label>Enter OTP</label>
            <input type="number" class="form-control" name="otp" placeholder="Enter OTP">
        </div>
        <div class="form-group">
        <label>Enter New Password</label>
            <input type="password" class="form-control" name="password" placeholder="Enter Password">
        </div>
        <div class="form-group">
        <label>Retype your Password</label>
            <input type="password" class="form-control" name="cpassword" placeholder="Enter Confirm Password">
        </div>
        <center>
        <button type="submit" class="btn" style="background-color:#660033;color: #F0E68C;"> &nbsp;&nbsp;&nbsp;&nbsp;Submit&nbsp;&nbsp; &nbsp;&nbsp;</button>
        </center>
    </form><br>
</div>
@endsection

resources/views/signup.blade.php
@extends('layouts.header')
@section('content')
<style>
    #btnhov:hover {
    background-color: yellow;
    }
</style>
<div class="col-md-8 col-md-offset-2" style="background-color:wheat; margin-top:50px; height: auto; box-shadow: 2px 2px 5px #660033;">
    <br><br><center><img src="img/signup.png" style="width:auto;"><br><legend style="color:#660033;"><strong>Signup Form</strong></legend></center>
<center>
@if ($message = Session::get('success'))
    <p style="color:green"><span class="glyphicon glyphicon-ok"></span> {{ $message }} <a href="/"> Login Page </a></p>
@endif
@if ($message = Session::get('error'))
    <p style="color:red">{{ $message }}</p>
@endif
</center>
    <form action="/users" method="POST">
    {{ csrf_field() }}
        <div class="form-group col-md-6">
            <label for="email">Username</label>
            <input type="text" class="form-control" name="username" placeholder="Enter your Username">
        </div>
        <div class="form-group col-md-6">
            <label for="email">Email Address</label>
            <input type="name" class="form-control" name="email" placeholder="Enter your Username">
        </div>
        <div class="form-group col-md-6">
            <label for="email">Password</label>
            <input type="password" class="form-control" name=password placeholder="Enter your Password">
        </div>
        <div class="form-group col-md-6">
            <label for="email">Confirm Password</label>
            <input type="password" class="form-control" name="cpassword" placeholder="Enter Confirm Password">
        </div>
        <div class="form-group col-md-4">
            <label for="email">Date of Birth</label>
            <input type="date" class="form-control" name="dob" placeholder="Enter your Username">
        </div>
        <div class="form-group col-md-4">
            <label for="email">Country</label>
            <select class="form-control" name="country">
                <option>Select</option>
                <?php for($i=0;$i<sizeof($countries);$i++){  ?>
                <option value="<?php echo $i ?>"><?php echo $countries[$i] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group col-md-4">
            <label for="email">Matrital Status</label>
            <select class="form-control" name="maritial_status">
                <option value="">Select</option>
                <option value="0">Single</option>
                <option value="1">Maried</option>
                <option value="2">In Realationship</option>
            </select>
        </div>
        <div class="form-group col-md-3">
        <label for="email">Gender</label><br>
            <label class="radio-inline"><input type="radio" name="gender" value="0">Male</label>
            <label class="radio-inline"><input type="radio" name="gender" value="1">Female</label>
        </div>
        <div class="form-group col-md-3">
            <label for="email">Language</label>
            <select class="form-control" name="lang">
                <option value="0">Select</option>
                <option value="1">Arabic</option>
                <option value="2">English</option>
                <option value="3">Chinese</option>
                <option value="4">Japanese</option>
                <option value="5">Spanish</option>
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="email">Employee</label>
            <select class="form-control" name="employee">
                <option value="0">Select</option>
                <option value="1">Student</option>
                <option value="2">Full Time Job</option>
                <option value="3">Part Time Job</option>
                <option value="4">Self Employed</option>
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="email">Currency</label>
            <select class="form-control" name="currency">
                <option value="0">Select</option>
                <?php for($i=0;$i<sizeof($currency);$i++){  ?>
                <option value="<?php echo $i ?>"><?php echo $currency[$i] ?></option>
                <?php } ?>
            </select>
        </div>
        <br><br>
        <p><input type="checkbox" name="optradio"> Check to accept and consent the moneytrackin' Terms of Use and Privacy Policy</p>
        <center><br>
        <button class="btn" id="btnhov" style=" width: 30%;background-color:#660033;color: #F0E68C">Sign up</button><br><br>
    </center>
    </form>
</div>
@endsection

resources/views/with_in_account.blade.php
@extends('layouts.header')
@section('content')


<style>
h3{
    color:white;
}
ul li{
    list-style:none;
}
#snav{
    width:100%;
    margin-left:-40px;
    margin-bottom:2px;
}

</style>
<script>
function myFun()
{
    var data = document.getElementById('sid').value;
    if(data == 1)
    {
        document.getElementById('aid').innerHTML="Enter Credit Amount";
        document.getElementById("textid").disabled = true; 
    }
    else{
        document.getElementById('aid').innerHTML="Enter Debit Amount";
        document.getElementById("textid").disabled = false; 
    }
}
</script>
@extends('layouts.side')
<!-- #######################   Profile Division      #################### -->
<div class="col-md-9" style="background-color: white; height: 96vh;">
<br>
<div class="col-md-8 col-md-offset-2" style="background-color: white;box-shadow:1px 1px 5px black; height: auto;">
<center>
<img src="https://cdn3.iconfinder.com/data/icons/e-commerce-trading/512/transaction_A-512.png" style="width:12%;">
<h4>Debit or Credit</h4>
<center>
@if ($message = Session::get('success'))
    <p style="color:green"><span class="glyphicon glyphicon-ok"></span> {{ $message }}</p>
    <script> myFun();</script>
@endif
@if ($message = Session::get('error'))
    <p style="color:red"><span class="glyphicon glyphicon-remove"></span> {{ $message }}</p>
@endif
</center>
<hr>
</center>
<form action="{{ route('accounts.update', Auth::user()->id) }}" method="POST">
{{ method_field('PUT') }}
    {{ csrf_field() }}
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="account">Transaction Type: </label>
    <select class="form-control" name="trans_type" id="sid" onchange="myFun()">
    <option value="null">Select</option>
    <option value="0">Debit</option>
    <option value="1">Credit</option>
    </select>
  </div><br>
  <div class="form-group col-md-8 col-md-offset-2">
    <label for="account">Select Account</label>
    <select class="form-control" name="to_account">
    <option>Select</option>
    @foreach($accounts_data as $user)
        <option value="{{ $user->name}}">{{ $user->name }}</option>
    @endforeach
    </select>
  </div><br>
  <div class="form-group col-md-8 col-md-offset-2">
    <label id="aid">Amount</label>
    <input type="number" class="form-control" name="amount_transfer" placeholder="Enter Amount">
  </div>
  <div class="form-group col-md-8 col-md-offset-2">
    <label id="tid">Description</label>
    <textarea type="text" id="did" class="form-control" name="description" placeholder="Enter description" required></textarea>
  </div>
  <div class="form-group col-md-8 col-md-offset-2">
    <label id="tid">Tags</label>
    <input type="text" id="textid" pattern="[a-z]+([,]+[a-z]+([a-z])?)*" class="form-control" name="tags" title="Seprate the tags with comma and lowercase only.Eg. health,vehicle" placeholder="Enter tags in lower case only using comma. Eg. food,health,vehicle" required>
  </div>
  <div class="form-group col-md-8 col-md-offset-2">Most Used Tags<br>
  <?php for($i=0;$i< sizeof($tags_top);$i++){?>
  <span class="label label-default" style="float:left; margin-left:2px;"> # <?php echo $tags_top[$i]; ?> </span>
  <?php } ?>
  </div>
  <center>
  <div class="form-group col-md-8 col-md-offset-5">
  <button type="submit" style="float:left; width:30%;" class="btn btn-success">Submit</button>
  </div>
  </center>
</form>
<br><br>

</div>

</div>
</div>@endsection